# Changes here will be overwritten by Copier
_commit: v0.5.0
_src_path: https://github.com/linkml/linkml-project-copier
add_example: false
copyright_year: '2026'
email: hncatanese@lbl.gov
existing_license_file: ''
full_name: Helen Catanese
gh_action_docs_preview: true
gh_action_pypi: true
github_org: ess-dive
license: Apache-2.0
project_description: Reviewed ESS-DIVE Dataset metadata schema and documentation
project_name: essdive-linkml-schemas
project_slug: essdive_metadata_schemas
