[project]
name = "ess-dive-schemas"
version = "0.1.0"
description = "Extract and publish ESS-DIVE Dataset metadata schemas."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "linkml-runtime>=1.11.1",
    "schema-automator>=0.5.7",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "coverage>=7.16.1",
]
